### ISSUE TITLE
Bombay Index - Data seems to be mismatching with real time data as shown in BSE Index website against HighCharts

### ISSUE THREAD

**Issue by arnabk** [binary-com/webtrader#15]
<a href="https://github.com/parashusg"><img src="https://avatars.githubusercontent.com/u/12329842?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [parashusg](https://github.com/parashusg)**
_Wednesday Jun 03, 2015 at 18:55 GMT_
_Originally opened as https://github.com/regentmarkets/highcharts/issues/22_

----

Bombay Index - Data seems to be mismatching with real time data as shown in BSE Index website against HighCharts

BOMBAY INDEX - I have visited BSE Index website and verified the data displayed in their charting against the data provided in HighCharts it seems to be slightly different, please check once. 
[Instruments | Indices | Asia/ Oceania | Bombay Index]

![bombayindex_livesite_valuediffers](https://cloud.githubusercontent.com/assets/12329842/7968742/1cf05a52-0a50-11e5-900c-0d960b7a80d1.JPG)
![highcharts_bombayindex_4pm](https://cloud.githubusercontent.com/assets/12329842/7968743/1dd68680-0a50-11e5-80b8-138d4d7cd828.JPG)

**Comment by arnabk** [comment]
@kavehmz @jy-binary Can we really try to match our OHLC with data obtained from other websites? If not, I will mark it as invalid

**Comment by yngshan** [comment]
I will work on this . I know where is the issue come from.

**Comment by arnabk** [comment]
@yngshan Any update on this?

**Comment by yngshan** [comment]
@arnabk , sorry for the delay. Have been working on other thing this week . Will work on it next week

**Comment by yngshan** [comment]
This is fixed. Please verified.

To compare the daily ohlc , you need to look at the chart with 1d interval. Looking at 15minutes, the close might not be matching with official close. Reason being , that is just the close at the 15 minute interval, but the official close might come slightly later

**Comment by arnabk** [comment]
@yngshan Thanks. I sent an email to Parashuram to verify this.

**Comment by parashusg** [comment]
@arnabk , @yngshan - I have verified the data for 1D interval and found to be workng fine with past dates till today however, if the data is not sync with 1 Min, 15 Min intervals then it looks like Highcharts within Binary site will not be in sync with Live server of bombay exchange. 
Is there a way so that I can correlate with realistic values? 
As end user my expectation will be - atleast I should be seeing the same values / closely equally to the BSE index site. 
As I am testing this - It's 9 Hours since BSE index market is closed still there is a difference in the values in Highcharts, But past dates like 3rd Nov, 2nd Nov are showing correct values.

![highcharts_ohlc_1d](https://cloud.githubusercontent.com/assets/12329842/10949301/27142a5a-8358-11e5-9f88-bc733610b37d.png)

Summary- 
1. How can I validate the 1 Min, 15 M interval values with BSE INDEX on Bomby Stock Exchng Site? 
2. If a market is closed 4PM and its 1:00 AM still data is not in Sync. 
![highcharts_ohlc_4nov_closure](https://cloud.githubusercontent.com/assets/12329842/10949415/bb89fd86-8358-11e5-98c9-afa3f1dcfe46.png)

**Comment by yngshan** [comment]
@parashusg send you an reply on email

**Comment by arnabk** [comment]
Closing as per the conclusion in email conversation
